/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;
import proyecto.pkg2.Funciones;
import proyecto.pkg2.HashTable;
import proyecto.pkg2.ListaEnlazada;
import proyecto.pkg2.NodoHash;

/**
 *
 * @author Kevin
 */
public class Principal extends javax.swing.JFrame {

    boolean archivo;
    Funciones f;
    HashTable hashTable;
    ListaEnlazada lista;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        f = new Funciones();
        hashTable = new HashTable(10111);
        lista = new ListaEnlazada();
        archivo = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leerDocumento = new javax.swing.JButton();
        contarRep = new javax.swing.JButton();
        buscarPalabra = new javax.swing.JButton();
        palabrasUsuales = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        verificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leerDocumento.setText("Leer documento");
        leerDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(leerDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 160, -1));

        contarRep.setText("Contar repeticiones");
        contarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contarRepActionPerformed(evt);
            }
        });
        jPanel1.add(contarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 160, -1));

        buscarPalabra.setText("Buscar palabra");
        buscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(buscarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 160, -1));

        palabrasUsuales.setText("Palabras más usadas");
        palabrasUsuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabrasUsualesActionPerformed(evt);
            }
        });
        jPanel1.add(palabrasUsuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 160, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 160, -1));

        verificar.setText("Verificar originalidad");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        jPanel1.add(verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerDocumentoActionPerformed
        String texto = f.leerTxtCargado();
        if (!texto.isBlank() || !texto.isEmpty()) {
            archivo = true;
            String[] array = f.soloPalabrasArray(texto);
            for (int i = 0; i < array.length; i++) {

                hashTable.insertar(array[i].replace("\n", "").replace(" ", ""), lista);
            }

        } else {
            archivo = false;
        }
    }//GEN-LAST:event_leerDocumentoActionPerformed

    private void contarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contarRepActionPerformed
        if (archivo) {

            String repeticiones = lista.imprimirLista();
            MostrarPalabras mostrar = new MostrarPalabras(repeticiones);
            lista.imprimirLista();

        } else {
            JOptionPane.showMessageDialog(null, "No se ha cargado ningún documento");
        }
    }//GEN-LAST:event_contarRepActionPerformed

    private void buscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPalabraActionPerformed
        if (archivo) {

            String palabra = JOptionPane.showInputDialog("Ingrese la palabra que quiere buscar: ");
            NodoHash buscado = hashTable.buscar(palabra);
            JOptionPane.showMessageDialog(null, "\"" + buscado.getPalabra() + "\" : " + buscado.getCount());

        } else {
            JOptionPane.showMessageDialog(null, "No se ha cargado ningún documento");
        }

    }//GEN-LAST:event_buscarPalabraActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void palabrasUsualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabrasUsualesActionPerformed
        if (archivo) {
            lista.ordenarLista();
            String masUsuales = lista.imprimirLista();
            MostrarPalabras mostrar = new MostrarPalabras(masUsuales);

        } else {
            JOptionPane.showMessageDialog(null, "No se ha cargado ningún documento");
        }
    }//GEN-LAST:event_palabrasUsualesActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        new VerificarOriginalidad().setVisible(true);
        dispose();
    }//GEN-LAST:event_verificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarPalabra;
    private javax.swing.JButton contarRep;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leerDocumento;
    private javax.swing.JButton palabrasUsuales;
    private javax.swing.JButton salir;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
