/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;
import proyecto.pkg2.Funciones;
import proyecto.pkg2.RabinKarp;

/**
 *
 * @author Kevin
 */
public class VerificarOriginalidad extends javax.swing.JFrame {

    String texto;
    boolean archivo;
    Funciones f;

    /**
     * Creates new form VerificarOriginalidad
     */
    public VerificarOriginalidad() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        f = new Funciones();
        fragmento.setLineWrap(true);
        fragmento.setWrapStyleWord(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargarArticulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        verificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fragmento = new javax.swing.JTextArea();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarArticulo.setText("Cargar artículo");
        cargarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(cargarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 160, -1));

        jLabel1.setText("Ingrese el fragmento a verificar: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        verificar.setText("Verificar");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        jPanel1.add(verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 110, -1));

        fragmento.setColumns(20);
        fragmento.setRows(5);
        fragmento.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jScrollPane1.setViewportView(fragmento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 390, 120));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        if (archivo && !fragmento.getText().isBlank() && !fragmento.getText().isEmpty()) {
            RabinKarp rk = new RabinKarp();
            String patron = fragmento.getText();

            String verificado = rk.indices(patron.toLowerCase(), texto);
            if (!verificado.isBlank() || !verificado.isEmpty()) {
                MostrarPalabras mp = new MostrarPalabras(verificado);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron coincidencias.");
            }
           
            
            

        }
    }//GEN-LAST:event_verificarActionPerformed

    private void cargarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArticuloActionPerformed
        this.texto = f.leerTxtCargado();
        if (!texto.isBlank() || !texto.isEmpty()) {
            archivo = true;

        } else {
            archivo = false;
        }
    }//GEN-LAST:event_cargarArticuloActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarArticulo;
    private javax.swing.JTextArea fragmento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
